### ISSUE TITLE
So where can I get this Debian package?

### ISSUE THREAD

**Issue by Redsandro** [dlecan/freefilesync-debian-package#1]
Looking left and right, google and duckduckgo.. where are these Debian packages, or apt repositories even, for FreeFileSync?

Might want to put that in the github repository readme. :)

**Comment by dlecan** [comment]
For Debian : nowhere
I don't have the infrastructure to build and publish Debian packages.
I tried to upload it to Debian repository several times, no success.

For Ubuntu, they can be found here:
https://launchpad.net/~freefilesync/+archive/ffs

> Might want to put that in the github repository readme. :)

Thank you. It has been updated.

**Comment by Redsandro** [comment]
Thanks for the reply.

That's unfortunate. I migrated one of my systems to Debian, only to find out that certain packages are not as easy to find as for it's "little brother" Ubuntu.

**Comment by Redsandro** [comment]
Not sure if this helps, but [Zenju](https://sourceforge.net/u/zhnmju123/profile/) did start building [Debian builds as of 5.15](https://sourceforge.net/projects/freefilesync/files/freefilesync/v5.15/). But only [for now](https://sourceforge.net/p/freefilesync/feature-requests/384/). Consider it a popularity contest. These are **.tar.gz** archives. Does this help with getting **.deb** Debian packages?

**Comment by dlecan** [comment]
> Does this help with getting .deb Debian packages?

Unfortunately, no.

If you need .deb for Debian, please help me to find two Debian sponsors to review FFS Debian package and toupload it into Debian repositories.
I haven't succeeded in two years ...

**Comment by Redsandro** [comment]
It is weirdly difficult to achieve this.
